[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kavya"
version = "0.2.0"
description = "A framework for serving and evaluating large language model routers."
readme = "README.md"
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
	'importlib-metadata; python_version<"3.10"',
	'pyyaml',
	'pydantic',
	'openai',
	'litellm==1.67.0'
]

[project.optional-dependencies]
serve = ["fastapi", "shortuuid", "uvicorn"]
eval = ["matplotlib", "pandarallel", "sglang", 'tiktoken']
dev = ["black", "isort", "pre-commit"]

[project.urls]
"Homepage" = "https://github.com/dxpr/Kavya"
"Bug Tracker" = "https://github.com/dxpr/Kavya"

[tool.isort]
profile = "black"

[tool.setuptools.packages.find]
exclude = ["assets*", "benchmarks*"]

[tool.wheel]
exclude = ["assets*", "benchmarks*"]

[tool.setuptools.package-data]
"kavya" = ["docs/litellm/**/*", "docs/pydantic/**/*", "docs/google-cloud-sql/**/*"]

[tool.setuptools]
script-files = ["scripts/download_docs.py"]

[project.scripts]
download-litellm-docs = "scripts.download_docs:download_all_docs"