name: Deploy to Scaleway

on:
  push:
    tags:
      - 'v*'

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v2
        with:
          registry: rg.nl-ams.scw.cloud
          username: ${{ secrets.SCW_ACCESS_KEY }}
          password: ${{ secrets.SCW_SECRET_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            rg.nl-ams.scw.cloud/${{ secrets.SCW_NAMESPACE }}/kavya:${{ github.ref_name }}
            rg.nl-ams.scw.cloud/${{ secrets.SCW_NAMESPACE }}/kavya:latest

      - name: Deploy to Scaleway Serverless Container
        uses: yamatt/scaleway-serverless-container-deploy-action@v1.1
        with:
          container_id: ${{ secrets.SCW_CONTAINER_ID }}
          secret_key: ${{ secrets.SCW_SECRET_KEY }}
          registry_image_url: rg.nl-ams.scw.cloud/${{ secrets.SCW_NAMESPACE }}/kavya:latest
          region: nl-ams